name: macOS

on: [push]

jobs:
  build-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: install-build-dependencies
      run: brew install eigen qt
    - name: submodule
      run: git submodule update --init --recursive
    - name: build-test-library
      run: |
        cmake -DSEQUENTIAL_LINE_SEARCH_BUILD_COMMAND_DEMOS=OFF -DSEQUENTIAL_LINE_SEARCH_BUILD_VISUAL_DEMOS=OFF -DSEQUENTIAL_LINE_SEARCH_BUILD_PHOTO_DEMOS=OFF -DSEQUENTIAL_LINE_SEARCH_BUILD_PYTHON_BINDING=OFF .
        make
    - name: build-test-apps
      run: |
        cmake -DSEQUENTIAL_LINE_SEARCH_BUILD_COMMAND_DEMOS=ON -DSEQUENTIAL_LINE_SEARCH_BUILD_VISUAL_DEMOS=ON -DSEQUENTIAL_LINE_SEARCH_BUILD_PHOTO_DEMOS=ON -DSEQUENTIAL_LINE_SEARCH_BUILD_PYTHON_BINDING=OFF .
        make
    - name: ctest
      run: ctest
